cd normal_smallMFM_3b
condor_submit condor_submit.sh
cd ../normal_smallMFM_4b
condor_submit condor_submit.sh
cd ../normal_smallMFM_5b
condor_submit condor_submit.sh
cd ../variation_bodymass_down_smallMFM_1b
condor_submit condor_submit.sh
cd ../variation_bodymass_down_smallMFM_2b
condor_submit condor_submit.sh
cd ../variation_bodymass_down_smallMFM_3b
condor_submit condor_submit.sh
cd ../variation_bodymass_down_smallMFM_4b
condor_submit condor_submit.sh
cd ../variation_bodymass_down_smallMFM_5b
condor_submit condor_submit.sh
cd ../variation_bodymass_up_smallMFM_1b
condor_submit condor_submit.sh
cd ../variation_bodymass_up_smallMFM_2b
condor_submit condor_submit.sh
cd ../variation_bodymass_up_smallMFM_3b
condor_submit condor_submit.sh
cd ../variation_bodymass_up_smallMFM_4b
condor_submit condor_submit.sh
cd ../variation_bodymass_up_smallMFM_5b
condor_submit condor_submit.sh
cd ../variation_cusp_down_smallMFM_1b
condor_submit condor_submit.sh
cd ../variation_cusp_down_smallMFM_2b
condor_submit condor_submit.sh
cd ../variation_cusp_down_smallMFM_3b
condor_submit condor_submit.sh
cd ../variation_cusp_up_smallMFM_1b
condor_submit condor_submit.sh
cd ../variation_cusp_up_smallMFM_2b
condor_submit condor_submit.sh
cd ../variation_cusp_up_smallMFM_3b
condor_submit condor_submit.sh
cd ../variation_numbody_down_smallMFM_1b
condor_submit condor_submit.sh
cd ../variation_numbody_down_smallMFM_2bb
condor_submit condor_submit.sh
cd ../variation_numbody_down_smallMFM_3b
condor_submit condor_submit.sh
cd ../variation_numbody_down_smallMFM_4b
condor_submit condor_submit.sh
cd ../variation_numbody_down_smallMFM_5b
condor_submit condor_submit.sh
cd ../variation_numbody_up_smallMFM_1b
condor_submit condor_submit.sh
cd ../variation_numbody_up_smallMFM_2b
condor_submit condor_submit.sh
cd ../variation_numbody_up_smallMFM_3b
condor_submit condor_submit.sh
cd ../variation_numbody_up_smallMFM_4b
condor_submit condor_submit.sh
cd ../variation_numbody_up_smallMFM_5b
condor_submit condor_submit.sh
