cp -f param_smallMFM.in normal_smallMFM_1b/param.in
cp -f param_smallMFM.in normal_smallMFM_2b/param.in
cp -f param_smallMFM.in normal_smallMFM_3b/param.in
cp -f param_smallMFM.in normal_smallMFM_4b/param.in
cp -f param_smallMFM.in normal_smallMFM_5b/param.in
cp -f param_smallMFM.in variation_bodymass_down_smallMFM_1b/param.in
cp -f param_smallMFM.in variation_bodymass_down_smallMFM_2b/param.in
cp -f param_smallMFM.in variation_bodymass_down_smallMFM_3b/param.in
cp -f param_smallMFM.in variation_bodymass_down_smallMFM_4b/param.in
cp -f param_smallMFM.in variation_bodymass_down_smallMFM_5b/param.in
cp -f param_smallMFM.in variation_bodymass_up_smallMFM_1b/param.in
cp -f param_smallMFM.in variation_bodymass_up_smallMFM_2b/param.in
cp -f param_smallMFM.in variation_bodymass_up_smallMFM_3b/param.in
cp -f param_smallMFM.in variation_bodymass_up_smallMFM_4b/param.in
cp -f param_smallMFM.in variation_bodymass_up_smallMFM_5b/param.in
cp -f param_smallMFM.in variation_cusp_down_smallMFM_1b/param.in
cp -f param_smallMFM.in variation_cusp_down_smallMFM_2b/param.in
cp -f param_smallMFM.in variation_cusp_down_smallMFM_3b/param.in
cp -f param_smallMFM.in variation_cusp_up_smallMFM_1b/param.in
cp -f param_smallMFM.in variation_cusp_up_smallMFM_2b/param.in
cp -f param_smallMFM.in variation_cusp_up_smallMFM_3b/param.in
cp -f param_smallMFM.in variation_numbody_down_smallMFM_1b/param.in
cp -f param_smallMFM.in variation_numbody_down_smallMFM_2bb/param.in
cp -f param_smallMFM.in variation_numbody_down_smallMFM_3b/param.in
cp -f param_smallMFM.in variation_numbody_down_smallMFM_4b/param.in
cp -f param_smallMFM.in variation_numbody_down_smallMFM_5b/param.in
cp -f param_smallMFM.in variation_numbody_up_smallMFM_1b/param.in
cp -f param_smallMFM.in variation_numbody_up_smallMFM_2b/param.in
cp -f param_smallMFM.in variation_numbody_up_smallMFM_3b/param.in
cp -f param_smallMFM.in variation_numbody_up_smallMFM_4b/param.in
cp -f param_smallMFM.in variation_numbody_up_smallMFM_5b/param.in
