cp -f normal_smallMFM_1/*{.in,.sh,param_*} normal_smallMFM_1b/
cp -f normal_smallMFM_2/*{.in,.sh,param_*} normal_smallMFM_2b/
cp -f normal_smallMFM_3/*{.in,.sh,param_*} normal_smallMFM_3b/
cp -f normal_smallMFM_4/*{.in,.sh,param_*} normal_smallMFM_4b/
cp -f normal_smallMFM_5/*{.in,.sh,param_*} normal_smallMFM_5b/
cp -f variation_bodymass_down_smallMFM_1/*{.in,.sh,param_*} variation_bodymass_down_smallMFM_1b/
cp -f variation_bodymass_down_smallMFM_2/*{.in,.sh,param_*} variation_bodymass_down_smallMFM_2b/
cp -f variation_bodymass_down_smallMFM_3/*{.in,.sh,param_*} variation_bodymass_down_smallMFM_3b/
cp -f variation_bodymass_down_smallMFM_4/*{.in,.sh,param_*} variation_bodymass_down_smallMFM_4b/
cp -f variation_bodymass_down_smallMFM_5/*{.in,.sh,param_*} variation_bodymass_down_smallMFM_5b/
cp -f variation_bodymass_up_smallMFM_1/*{.in,.sh,param_*} variation_bodymass_up_smallMFM_1b/
cp -f variation_bodymass_up_smallMFM_2/*{.in,.sh,param_*} variation_bodymass_up_smallMFM_2b/
cp -f variation_bodymass_up_smallMFM_3/*{.in,.sh,param_*} variation_bodymass_up_smallMFM_3b/
cp -f variation_bodymass_up_smallMFM_4/*{.in,.sh,param_*} variation_bodymass_up_smallMFM_4b/
cp -f variation_bodymass_up_smallMFM_5/*{.in,.sh,param_*} variation_bodymass_up_smallMFM_5b/
cp -f variation_cusp_down_smallMFM_1/*{.in,.sh,param_*} variation_cusp_down_smallMFM_1b/
cp -f variation_cusp_down_smallMFM_2/*{.in,.sh,param_*} variation_cusp_down_smallMFM_2b/
cp -f variation_cusp_down_smallMFM_3/*{.in,.sh,param_*} variation_cusp_down_smallMFM_3b/
cp -f variation_cusp_up_smallMFM_1/*{.in,.sh,param_*} variation_cusp_up_smallMFM_1b/
cp -f variation_cusp_up_smallMFM_2/*{.in,.sh,param_*} variation_cusp_up_smallMFM_2b/
cp -f variation_cusp_up_smallMFM_3/*{.in,.sh,param_*} variation_cusp_up_smallMFM_3b/
cp -f variation_numbody_down_smallMFM_1/*{.in,.sh,param_*} variation_numbody_down_smallMFM_1b/
cp -f variation_numbody_down_smallMFM_2b/*{.in,.sh,param_*} variation_numbody_down_smallMFM_2bb/
cp -f variation_numbody_down_smallMFM_3/*{.in,.sh,param_*} variation_numbody_down_smallMFM_3b/
cp -f variation_numbody_down_smallMFM_4/*{.in,.sh,param_*} variation_numbody_down_smallMFM_4b/
cp -f variation_numbody_down_smallMFM_5/*{.in,.sh,param_*} variation_numbody_down_smallMFM_5b/
cp -f variation_numbody_up_smallMFM_1/*{.in,.sh,param_*} variation_numbody_up_smallMFM_1b/
cp -f variation_numbody_up_smallMFM_2/*{.in,.sh,param_*} variation_numbody_up_smallMFM_2b/
cp -f variation_numbody_up_smallMFM_3/*{.in,.sh,param_*} variation_numbody_up_smallMFM_3b/
cp -f variation_numbody_up_smallMFM_4/*{.in,.sh,param_*} variation_numbody_up_smallMFM_4b/
cp -f variation_numbody_up_smallMFM_5/*{.in,.sh,param_*} variation_numbody_up_smallMFM_5b/
